name: dash
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  syncfusion_flutter_sliders: ^20.2.44
  flutter_svg: ^1.1.0
  syncfusion_flutter_charts: ^20.2.46
  flutter_launcher_icons: ^0.10.0
  led_bulb_indicator: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/icons/
     - assets/tables/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/iconHydro.jpeg"
  web:
    generate: true
    image_path: "assets/icons/iconHydro.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
    windows:
      generate: true
      image_path: "assets/icons/rushydro.jpeg"
      icon_size: 48

  fonts:
     - family: Manrope
       fonts:
         - asset: assets/fonts/Manrope-Regular.ttf
           weight: 600
         - asset: assets/fonts/Manrope-Light.ttf
           weight: 500
         - asset: assets/fonts/Manrope-Bold.ttf
           weight: 800
